### PR TITLE
WIP: App Loading

### PR DESCRIPTION
**Pull request by crc-32**
Uses nx-hbloader ABI in order to launch installed apps when possible

### CODE REVIEW

**Comment by crc-32** [comment]
Will require vgmoose/libget#15

**Comment by vgmoose** [comment]
I wonder if there's a better place to put the launch button instead of the sidebar?

I was thinking maybe a light-theme'd smaller button to the left of the sidebar, in the bottom right of the description (but also floating above the scrollable area and always on screen)

Or maybe the answer is to move the (B) Back button somewhere else, as there's no real reason that it needs to be that large and prominent

**Comment by crc-32** [comment]
@vgmoose could move back to bottom right of description, or perhaps remove it entirely as it's usually implied B is the back button

**Comment by vgmoose** [comment]
I can play around with some positioning stuff, thanks again for this!

**Pull request merged**
