### PR TITLE
Full Turkish Language Support

### PR DESCRIPTION
**Pull request by MYusufY**
I have been translating till like 5-6 hours, to make this good program even better :) Thanks for all of you guys! And also, i want to do other contribitions to HB app store, i dont want to just "translate" it. So if there is an idea about adding something to HB app store, im here :) I just want to contribute!!! Thanks again :)

### CODE REVIEW

**Comment by vgmoose** [comment]
Thank you! Looks good from what I can tell. I’ll merge this in shortly.

Were you able to test the changes in a custom build? I think it might make it easier if I add support for loading the ini from SD card to make translating easier.

**Comment by MYusufY** [comment]
Thanks! Thanks to you guys for this good program. I will test it in shortly 🙂 And yes, loading language .ini files might be pretty good to translators :) Maybe... this is the idea i want? Like i said, i need to do more contributions :) Thanks again 😊

**Comment by MYusufY** [comment]
And... if there is no problem, i have a simple question. How can the people download this version with Turkish language support after merging? In action tab, it gives linux, mac and windows apps only? And, is it directly going to homebrew app store as an update after merging or not? Thanks!

**Comment by MYusufY** [comment]
Also, i almost forgot to say, i had to change the "joke" part a little bit, because its not that "common" in our county, there can be misunderstoods :) So i made a "popular" one :) If you want to change it to original french fries anyways, i can do of course!

**Comment by MYusufY** [comment]
@vgmoose if there is anything you want to ask me about translation or change, feel free! Are you going to merge it? (Also, i did some small updates with one more commit. :) )

**Comment by vgmoose** [comment]
> How can the people download this version with Turkish language support after merging? 

The next version of hb-appstore will detect the wiiu/switch system language, and allow the user to override it in settings, but I am still working on this.

Changing the joke is totally fine, I think it's a nice touch that translators will be able to pick their own "proverb" for that error screen / recovery mode!

I'm merging it now, and you can expect it to be in the next 2.4 version of hb-appstore. This was supposed to come out end of April but has been pushed back. These are the remaining tasks: https://github.com/fortheusers/hb-appstore/issues?q=is%3Aopen+is%3Aissue+label%3A2.4-release

**Comment by MYusufY** [comment]
@vgmoose thanks a lot for all of these informations and also sorry for too many questions ☺️

**Review by Agrament — APPROVED** [review]

**Review by Agrament — APPROVED** [review]

**Pull request merged**
